# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffcccc67560a47a21a707e85b01cf80996956cf5edd9750ceb9f9d0470dc7bf441806ae02f5797cb497617845e0f49b6b081fc3afeb5f8724ea9e4a0200a822a

test:
  secret_key_base: ae3c67405f0167c8b84f6c148bca7c8521786bec7843592ce20d7891ba8a5d3329abf94fedb7c30771366ebd48f1e8a9196abbbf3844785a4411d0f121139e68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
